FIXUP: CHROMIUM: FROMLIST: clk: mediatek: Export CPU mux clocks for CPU frequency control
Upstream __clk_get_num_parents changed to clk_cpumux_get_parent.

drivers/clk/mediatek/clk-cpumux.c: In function 'clk_cpumux_get_parent':
drivers/clk/mediatek/clk-cpumux.c:38:2: error: implicit declaration of function '__clk_get_num_parents' [-Werror=implicit-function-declaration]
  int num_parents = __clk_get_num_parents(hw->clk);

Change-Id: I16300b634b1aa029d2a1f7a9511139849f5be646
Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>